export const CATEGORIES = [
  {
    id: 'top-stories',
    label: '🔥 Top Stories',
    emoji: '🔥',
    type: 'top-headlines',
    params: { country: 'us', category: 'general' },
  },
  {
    id: 'ai',
    label: '🤖 AI',
    emoji: '🤖',
    type: 'everything',
    params: { q: 'artificial intelligence OR ChatGPT OR OpenAI OR LLM', sortBy: 'publishedAt', language: 'en' },
  },
  {
    id: 'tech',
    label: '💻 Tech',
    emoji: '💻',
    type: 'top-headlines',
    params: { country: 'us', category: 'technology' },
  },
  {
    id: 'business',
    label: '💼 Business',
    emoji: '💼',
    type: 'top-headlines',
    params: { country: 'us', category: 'business' },
  },
  {
    id: 'money-finance',
    label: '💰 Money & Finance',
    emoji: '💰',
    type: 'everything',
    params: { q: 'finance OR economy OR Federal Reserve OR inflation', sortBy: 'publishedAt', language: 'en' },
  },
  {
    id: 'stocks',
    label: '📈 Stocks',
    emoji: '📈',
    type: 'everything',
    params: { q: 'stock market OR S&P 500 OR NASDAQ OR Wall Street', sortBy: 'publishedAt', language: 'en' },
  },
  {
    id: 'health',
    label: '🏥 Health',
    emoji: '🏥',
    type: 'top-headlines',
    params: { country: 'us', category: 'health' },
  },
  {
    id: 'world-politics',
    label: '🌍 World & Politics',
    emoji: '🌍',
    type: 'top-headlines',
    params: { sources: 'bbc-news,reuters,associated-press' },
  },
  {
    id: 'war-geopolitics',
    label: '⚔️ War & Geopolitics',
    emoji: '⚔️',
    type: 'everything',
    params: { q: 'war OR conflict OR military OR NATO OR Ukraine OR Gaza', sortBy: 'publishedAt', language: 'en' },
  },
  {
    id: 'companies',
    label: '🏢 Companies',
    emoji: '🏢',
    type: 'everything',
    params: { q: 'company earnings OR startup funding OR acquisition OR IPO', sortBy: 'publishedAt', language: 'en' },
  },
  {
    id: 'social-media',
    label: '📱 Social Media',
    emoji: '📱',
    type: 'everything',
    params: { q: 'TikTok OR Instagram OR X Twitter OR Meta OR social media', sortBy: 'publishedAt', language: 'en' },
  },
  {
    id: 'trends',
    label: '🌐 Trends',
    emoji: '🌐',
    type: 'everything',
    params: { q: 'viral OR trending OR world record OR breakthrough', sortBy: 'publishedAt', language: 'en' },
  },
  {
    id: 'videos',
    label: '🎬 Videos',
    emoji: '🎬',
    type: 'videos',
    params: {},
  },
];

export const VIDEO_FEEDS = [
  { playlistId: 'UU16niRr50-MSBwiO3YDb3RA', label: '🌍 World News (BBC)' },
  { playlistId: 'UUC1XUFpQhJvC8mK15mE6Kkw', label: '🤖 AI News (Matt Wolfe)' },
  { playlistId: 'UUddiUEpeqJcYeBxX1IVBKvQ', label: '💻 Tech News (The Verge)' },
  { playlistId: 'UU8P0dc0Zn2gf8L6tJi_k6xg', label: '💼 Business (CNBC)' },
  { playlistId: 'UUMtPTVIwI7famjg2249GcpQ', label: '🔴 Breaking News (NBC)' },
  { playlistId: 'UUEAZeUIeJs0IjQiqTCdXTuQ', label: '📈 Stock Market (Yahoo)' },
];
